#!/bin/sh

PIDFILE=/tmp/shh.pid

shh_start () {
    play -n synth brownnoise gain -8 > /dev/null 2>&1 &
    echo $! > $PIDFILE
}

shh_stop () {
    pid=$(cat $PIDFILE)
    kill $pid
    rm $PIDFILE
}

shh_toggle () {
    if [ ! -f $PIDFILE ]; then
        shh_start
    else
        shh_stop
    fi
}

shh_toggle

exit 0
